In [1]:
'''
Chỉnh working directory, k cần quan tâm lắm :))
'''

import sys
from pathlib import Path
# Add the project root directory (one level up from tests/)
sys.path.append(str(Path.cwd().parent))
import pandas as pd
import os

In [57]:
'''
Load các thư viện, function cần thiết.
    producer_config: cài đặt filter do chuyên viên nhập và điều chỉnh
    LoadMedicalData: class sử dụng để load, xử lý và tính toán
'''
%load_ext autoreload
%autoreload 2

from config.filter_config import producer_config
from src.utils.data_loader import LoadMedicalData

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [ ]:
'''
Đoạn này thử đưa một đoạn dữ liệu vào để load. Sau khi chạy xong thì dữ liệu raw sẽ được lưu trong 'test_data'. Người dùng có thể thực hiện filter hoặc tính tổng từ đây.
'''

test_path = r'..\data\raw\data_Duoc_full\raw\kqtt\202504-202505.xls' # đưa PATH đến data ở đây. 
test_data = LoadMedicalData(
    test_path, 
    config=producer_config # Phần config này về sau sẽ cần mở rộng cho các dạng filter khác, hiện tại đang mới có filter dành cho 'nhasx'
)

In [ ]:
# Hiển thị toàn bộ dữ liệu raw
test_data.show_data()

In [60]:
# Filter dữ liệu tùy theo config đưa vào
test_data.filter().show_data() # Nếu để trống phần filter sẽ trả về toàn bộ các mục mà được liệt kê trong config

,loai_thau,ma,ten,hoatchat,ma_tinh,ten_tinh,ten_don_vi,ma_cskcb,ten_cskcb,ma_gy,...,sttpheduyet,hieuluc,ht_thau,created_date,tungay,denngay,congbo,tungay_hd,denngay_hd,ticker
0,3.thau_rieng_le,40.158,"Nerusyn 1,5g",Ampicilin + sulbactam,11,Tỉnh Điện Biên,Ttyt Điện Biên Phủ,11002,Ttyt Điện Biên Phủ,40.158,...,None,1,1,2025-10-25 22:21:51,2025-04-22,NaT,2025-04-22,2025-04-22,2027-04-22,IMP
1,3.thau_rieng_le,40.161,Imeclor 125,Cefaclor,60,Tỉnh Bình Thuận,Tyt Đa Mi,60097,Tyt Đa Mi,40.161,...,None,1,5,2025-10-25 22:21:51,2025-04-29,NaT,2025-04-29,2025-04-29,2026-01-29,IMP
2,3.thau_rieng_le,40.162,Imedroxil 500mg,Cefadroxil,94,Tỉnh Sóc Trăng,Tyt Trường Khánh,94132,Tyt Trường Khánh,40.162,...,None,1,4,2025-10-25 22:21:51,2025-05-16,NaT,2025-05-16,2025-05-16,2026-02-15,IMP
3,3.thau_rieng_le,40.169,Imexime 100,Cefixim,82,Tỉnh Tiền Giang,Pkđk Dưỡng Điềm Thuộc Ttyt Khu Vực Châu Thành,82025,Pkđk Dưỡng Điềm Thuộc Ttyt Khu Vực Châu Thành,40.169,...,None,1,1,2025-10-25 22:21:51,2025-05-15,NaT,2025-05-15,2025-05-15,2027-05-14,IMP
4,3.thau_rieng_le,40.155,"Amoxicillin 250 mg/ 31,25 mg",Amoxicilin + acid clavulanic,01,Thành phố Hà Nội,Pkđkkv Liên Hồng Trực Thuộc Tyt Ô Diên,01839,Pkđkkv Liên Hồng Trực Thuộc Tyt Ô Diên,40.155,...,None,1,1,2025-10-25 22:21:51,2025-04-22,NaT,2025-04-22,2025-04-22,2026-04-22,IMP
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8636,3.thau_rieng_le,40.1057,Vitamin C-OPC 100mg Hương cam,Vitamin C,27,Tỉnh Bắc Ninh,Bv Quân Y 110,27010,Bv Quân Y 110,40.1057,...,None,1,1,2025-10-25 22:21:51,2025-04-10,NaT,2025-04-10,2025-04-10,2025-10-31,OPC
8637,3.thau_rieng_le,40.1057,Vitamin C-OPC 100mg Hương cam,Vitamin C,27,Tỉnh Bắc Ninh,Bv Quân Y 110,27010,Bv Quân Y 110,40.1057,...,None,1,1,2025-10-25 22:21:51,2025-04-10,NaT,2025-04-10,2025-04-10,2025-10-31,OPC
8638,3.thau_rieng_le,40.69,Leolen Forte,Cytidin-5monophosphat disodium + uridin,01,Thành phố Hà Nội,Bvđk Đống Đa,01004,Bvđk Đống Đa,40.69,...,None,1,1,2025-10-25 22:21:51,2025-04-03,NaT,2025-04-03,2025-04-03,2026-04-02,OPC
8639,3.thau_rieng_le,40.619,Nước oxy già 3%,Nước oxy già,68,Tỉnh Lâm Đồng,Bvđk Tỉnh,68001,Bvđk Tỉnh,40.619,...,None,1,1,2025-10-25 22:21:51,2025-05-14,NaT,2025-05-14,2025-05-14,2026-11-14,OPC
8640,3.thau_rieng_le,40.619,Nước oxy già 3%,Nước oxy già,68,Tỉnh Lâm Đồng,Bvđk Tỉnh,68001,Bvđk Tỉnh,40.619,...,None,1,1,2025-10-25 22:21:51,2025-05-14,NaT,2025-05-14,2025-05-14,2026-11-14,OPC

In [61]:
# Filter ra một mục tùy chọn
test_data.filter(by='IMP').show_data()

,loai_thau,ma,ten,hoatchat,ma_tinh,ten_tinh,ten_don_vi,ma_cskcb,ten_cskcb,ma_gy,...,sttpheduyet,hieuluc,ht_thau,created_date,tungay,denngay,congbo,tungay_hd,denngay_hd,ticker
0,3.thau_rieng_le,40.158,"Nerusyn 1,5g",Ampicilin + sulbactam,11,Tỉnh Điện Biên,Ttyt Điện Biên Phủ,11002,Ttyt Điện Biên Phủ,40.158,...,None,1,1,2025-10-25 22:21:51,2025-04-22,NaT,2025-04-22,2025-04-22,2027-04-22,IMP
1,3.thau_rieng_le,40.161,Imeclor 125,Cefaclor,60,Tỉnh Bình Thuận,Tyt Đa Mi,60097,Tyt Đa Mi,40.161,...,None,1,5,2025-10-25 22:21:51,2025-04-29,NaT,2025-04-29,2025-04-29,2026-01-29,IMP
2,3.thau_rieng_le,40.162,Imedroxil 500mg,Cefadroxil,94,Tỉnh Sóc Trăng,Tyt Trường Khánh,94132,Tyt Trường Khánh,40.162,...,None,1,4,2025-10-25 22:21:51,2025-05-16,NaT,2025-05-16,2025-05-16,2026-02-15,IMP
3,3.thau_rieng_le,40.169,Imexime 100,Cefixim,82,Tỉnh Tiền Giang,Pkđk Dưỡng Điềm Thuộc Ttyt Khu Vực Châu Thành,82025,Pkđk Dưỡng Điềm Thuộc Ttyt Khu Vực Châu Thành,40.169,...,None,1,1,2025-10-25 22:21:51,2025-05-15,NaT,2025-05-15,2025-05-15,2027-05-14,IMP
4,3.thau_rieng_le,40.155,"Amoxicillin 250 mg/ 31,25 mg",Amoxicilin + acid clavulanic,01,Thành phố Hà Nội,Pkđkkv Liên Hồng Trực Thuộc Tyt Ô Diên,01839,Pkđkkv Liên Hồng Trực Thuộc Tyt Ô Diên,40.155,...,None,1,1,2025-10-25 22:21:51,2025-04-22,NaT,2025-04-22,2025-04-22,2026-04-22,IMP
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
757,3.thau_rieng_le,40.169,Imexime 100,Cefixim,26,Tỉnh Vĩnh Phúc,Ttyt Khu Vực Tam Đảo,26026,Ttyt Khu Vực Tam Đảo,40.169,...,None,1,1,2025-10-25 22:21:51,2025-04-03,NaT,2025-04-03,2025-04-03,2026-04-02,IMP
758,3.thau_rieng_le,40.172,Bacsulfo 1g/1g,Cefoperazon + sulbactam*,01,Thành phố Hà Nội,Bvđk Vân Đình,01817,Bvđk Vân Đình,40.172,...,None,1,1,2025-10-25 22:21:51,2025-04-04,NaT,2025-04-04,2025-04-04,2026-04-04,IMP
759,3.thau_rieng_le,40.155,"Amoxicillin/ Acid clavulanic 250 mg/ 31,25 mg",Amoxicilin + acid clavulanic,10,Tỉnh Lào Cai,Bvđk Số 4 Tỉnh Lào Cai,10009,Bvđk Số 4 Tỉnh Lào Cai,40.155,...,None,1,1,2025-10-25 22:21:51,2025-04-04,2026-04-03,2025-04-04,2025-04-04,2027-04-04,IMP
760,3.thau_rieng_le,40.171,"Cefoperazone 0,5g",Cefoperazon*,01,Thành phố Hà Nội,Bvđk Nông Nghiệp,01013,Bvđk Nông Nghiệp,40.171,...,None,1,1,2025-10-25 22:21:51,2025-05-14,NaT,2025-05-14,2025-05-14,2027-05-14,IMP
761,3.thau_rieng_le,40.174,Cefotiam1g,Cefotiam*,01,Thành phố Hà Nội,Bvđk Nông Nghiệp,01013,Bvđk Nông Nghiệp,40.174,...,None,1,1,2025-10-25 22:21:51,2025-05-14,NaT,2025-05-14,2025-05-14,2027-05-14,IMP

In [62]:
# Tính tổng số lượng
print(f'Tổng số lượng của IMP: {test_data.filter(by='IMP').sum(value_col='soluong'):,.0f}') # Cái ':,.0f' là để hiển thị dấu phẩy hàng nghìn
 
# Tính tổng giá trị
print(f'Tổng giá trị của IMP: {test_data.filter(by='IMP').sum(value_col='thanhtien'):,.0f}')

Tổng số lượng của IMP: 25,647,070
Tổng giá trị của IMP: 288,706,927,665

# Test

In [106]:
%load_ext autoreload
%autoreload 2

from config.filter_config import producer_config, country_config
from src.utils.data_loader import read_xml, filter_data

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [107]:
# test_path = r'..\data\raw\data_Duoc_full\raw\kqtt\202504-202505.xls' # đưa PATH đến data ở đây. 
# test_data = read_xml(test_path)

In [108]:
matched, unmatched = filter_data(test_data, country_config, verbose=True, return_unmatched=True)

=== BÁO CÁO MATCH DỮ LIỆU ===
Cột gán nhãn:       'country'
Tổng số dòng:       41,472
Đã match (gán nhãn): 41,464 (99.98%)
Chưa match:         8 (0.02%)

Chi tiết theo 'country':
country
Việt Nam       34403
Việt Nam         34393
Ấn Độ             1192
Pháp              1041
Đức                547
Tây Ban Nha        382
Hungary            373
Hàn Quốc           344
Slovenia           278
Ba Lan             270
Síp                260
Ý                  247
Romania            228
Bỉ                 169
Hoa Kỳ             165
Hy Lạp             164
Ireland            145
Thụy Điển          143
Áo                 130
Ukraine            102
Nhật Bản           100
Bồ Đào Nha          85
Bulgaria            67
Thái Lan            64
Úc                  52
Đài Loan            48
Thụy Sĩ             47
Trung Quốc          39
Bangladesh          38
Anh                 37
Indonesia           35
Thổ Nhĩ Kỳ          31
Malaysia            28
Pakistan            28
Hà Lan              27
Séc                 22
Bắc Macedonia       20
Latvia              19
Đan Mạch            17
Puerto Rico         12
Singapore           12
Slovakia            10
Malta                8
Canada               7
Nga                  6
Belarus              5
Na Uy                5
Phần Lan             4
Ai Cập               2
Chile                2
Croatia              2
Litva                2
Argentina            1
Estonia              1
==============================

In [109]:
# Hiển thị toàn bộ dữ liệu raw
sorted([str(x) for x in matched['nuocsx'].unique().tolist() if not None])

['"Việt Nam\n"',
 '"Việt Nam"',
 '(Đ/c: Waco, TX 76712 - USA)',
 '-CSSX: Đức\n- CS đóng gói thứ cấp: Đức',
 'Ai Cập',
 'Ailen',
 'Anh',
 'Argentina',
 'Australia',
 'Austria',
 'Ba Lan',
 'Bangladesh',
 'Belarus',
 'Belgium',
 'Bỉ',
 'Bulgaria',
 'Bungary',
 'Bỉ',
 'Bồ Đào Nha',
 'CSSX bán thành phẩm, đóng gói sơ cấp và thứ cấp: Ý; Cơ sở xuất xưởng: Đức',
 'CSSX, đóng gói, kiểm soát lô: - Ba Lan; CS xuất xưởng lô: Ba Lan',
 'CSSX, đóng gói, kiểm soát lô: Ba Lan; CS xuất xưởng lô: Ba Lan',
 'CSSX: Bồ Đào Nha; CSTG: Ý',
 'CSSX: Canada, CSĐG và xuất xưởng: Ireland',
 'CSSX: Germany; CSĐG: Austria',
 'CSSX: Mỹ, CS đóng gói và xuất xưởng lô: Anh',
 'CSSX: Mỹ, CSĐG và xuất xưởng lô: Anh',
 'CSSX: Mỹ, CSĐG: Anh',
 'CSSX: Mỹ, ĐG và XX: Đức',
 'CSSX: Mỹ, Đóng gói và xuất xưởng: Đức',
 'CSSX: Mỹ, đóng gói: Hà Lan',
 'CSSX: Mỹ; CSĐG: Anh',
 'CSSX: Pháp; Xuất xưởng: Đức',
 'CSSX: Puerto Rico, CSĐG và xuất xưởng: Hà Lan',
 'CSSX: Puerto Rico, đóng gói: Hà Lan',
 'CSSX: Thụy Sĩ; Đóng gói và xuất xưởng: Đức',
 'CSSX: Tây Ban Nha, CSĐG và xuất xưởng: Anh',
 'CSSX: Áo CSĐG: Áo',
 'CSSX: Áo; Xuất xưởng: Slovenia',
 'CSSX: Ý (CS KN: Ý)',
 'CSSX: Ý, đóng gói: Ý',
 'CSSX: Ý; CSTG: Ý',
 'CSSX: Ý; CSXX: Đức',
 'CSSX: Ý; CSĐG: Thụy Sỹ',
 'CSSX: Ý; Đóng gói và xuất xưởng: Thụy Sỹ',
 'CSSX: Đức, CSĐG: Áo',
 'CSSX: Đức; CSĐG và xuất xưởng: Áo',
 'CSSX: Đức; CSĐG và xuất xưởng: Đức',
 'CSSX: Đức; CSĐG: Thụy Sỹ',
 'CYPRUS',
 'Canada',
 'Chile',
 'China',
 'Croatia',
 'Cyprus',
 'Czech',
 'Czech Republic',
 'Công ty cổ phần dược phẩm Am Vi',
 'Cơ sở sản xuất và đóng gói: Thổ Nhĩ Kỳ; Cơ sở kiểm nghiệm và xuất xưởng: Pháp',
 'Cơ sở sản xuất, đóng gói và xuất xưởng: Ý; Cơ sở sản xuất bán thành phẩm: Bỉ',
 'Cơ sở sản xuất: Pháp\nCơ sở xuất xưởng: Pháp',
 'Cơ sở sản xuất: Đức\nCơ sở đóng gói và xuất xưởng: Thụy Sĩ',
 'Cơ sở sản xuất: Đức\nCơ sở đóng gói: Thụy Sĩ',
 'Cơ sở sản xuất: Đức; Cơ sở đóng gói và xuất xưởng: Slovenia',
 'Cơ sở sản xuất: Đức; Cơ sở đóng gói: Thụy Sĩ',
 'Cộng Hòa Séc',
 'Cộng hòa Séc',
 'Cộng hòa Síp',
 'Cộng hòa nhân dân Trung Hoa',
 'Egis-Hungary',
 'Estonia',
 'France',
 'Germany',
 'Greece',
 'Hoa Kỳ',
 'Hungari',
 'Hungary',
 'Hy Lạp',
 'Hà Lan',
 'Hàn Quốc',
 'Hàn quốc',
 'India',
 'India (Ấn Độ)',
 'Indonesia',
 'Ireland',
 'Ireland đóng gói Pháp',
 'Ireland; đóng gói và xuất xưởng: France',
 'Italia',
 'Italy',
 'Japan',
 'Korea',
 'Latvia',
 'Litva (Lithuania)',
 'Macedonia',
 'Malaysia',
 'Malta',
 'Mỹ',
 'Mỹ, đóng gói: Anh',
 'Mỹ, đóng gói: Hà Lan',
 'Mỹ, đóng gói: Đức',
 'Na Uy',
 'Nga',
 'Nhật',
 'Nhật Bản',
 'Nước sản xuất và đóng gói: Slovenia',
 'Nước sản xuất và đóng gói: Thổ Nhĩ Kỳ; Nước kiểm nghiệm và xuất xưởng: Pháp',
 'Nước sản xuất: Mỹ; Nước đóng gói: Anh',
 'Pakistan',
 'Pakistan (Việt Nam - Cơ sở đóng gói cấp 2)',
 'Pháp',
 'Pháp',
 'Pháp, đóng gói: Mỹ',
 'Phần Lan',
 'Poland',
 'Portugal',
 'Republic of Korea',
 'Romani',
 'Romania',
 'Rumani',
 'SX, ĐG, KN: Slovakia ; XX: Latvia',
 'Singapore',
 'Slovaka',
 'Slovakia',
 'Slovenia',
 'Spain',
 'Sweden',
 'Switzerland',
 'Síp',
 'Sản xuất, đóng gói, kiểm nghiệm: Slovakia ; Xuất xưởng: Latvia',
 'Taiwan',
 'Thailand',
 'The Netherlands',
 'Thụy Sỹ',
 'Thái Lan',
 'Thổ Nhĩ Kỳ',
 'Thụy Sĩ',
 'Thụy Sỹ',
 'Thụy Điển',
 'Trung\n  Quốc',
 'Trung Quốc',
 'Turkey',
 'Tây Ba Nha; Đóng gói: Anh',
 'Tây Ban Nha',
 'USA',
 'Ukraine',
 'United Kingdom',
 'VIỆT NAM',
 'Việt Nam',
 'Việt\nNam',
 'Việt \nNam',
 'Việt  Nam',
 'Việt Nam',
 'Việt Nam,',
 'Việt nam',
 'ViệtNam',
 'Ytaly',
 'Áo',
 'Áo; Đóng gói: Slovenia',
 'Áo; Đóng gói: Đức',
 'Úc',
 'Ý',
 'Ý, đóng gói Thụy Sỹ',
 'áo',
 'ý',
 'Đan Mạch',
 'Đài Loan',
 'Đài loan',
 'Đức',
 'Đức (CSĐG và XX: Đức)',
 'Đức (Cơ sở đóng gói và xuất xưởng: Đức)',
 'Đức, Áo',
 'Đức: Đóng gói Áo',
 'Ấn Độ',
 'Ấn độ']

In [110]:
sorted([str(x) for x in unmatched['nuocsx'].unique().tolist() if not None])

['Nước ngoài', 'Viên', 'nan']